# Generated by Django 4.0.3 on 2022-09-15 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Code1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('friend_id', models.AutoField(primary_key=True, serialize=False)),
                ('update', models.DateTimeField(auto_now=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('friends', models.ManyToManyField(blank=True, related_name='manyFriends', to='Code1.profile')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Code1.profile')),
            ],
        ),
    ]
