# Generated by Django 4.0.3 on 2022-09-16 13:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Room', '0004_room_name_room_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('mess_id', models.AutoField(primary_key=True, serialize=False)),
                ('context', models.TextField()),
                ('created', models.DateField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roomMes', to='Room.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userMes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
