# Generated by Django 4.0.3 on 2022-09-16 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Room', '0005_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='context',
            new_name='content',
        ),
    ]
