# Generated by Django 4.0.3 on 2022-09-15 06:32

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Code1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('answer_id', models.AutoField(primary_key=True, serialize=False)),
                ('body', ckeditor.fields.RichTextField()),
                ('code_1_type', models.CharField(blank=True, max_length=12, null=True, verbose_name='Code 1 Lang')),
                ('code_1', models.TextField(blank=True, null=True, verbose_name='CodeBlock 1')),
                ('code_2_type', models.CharField(blank=True, max_length=12, null=True, verbose_name='Code 2 Lang')),
                ('code_2', models.TextField(blank=True, null=True, verbose_name='CodeBlock 2')),
                ('code_3_type', models.CharField(blank=True, max_length=12, null=True, verbose_name='Code 3 Lang')),
                ('code_3', models.TextField(blank=True, null=True, verbose_name='CodeBlock 3')),
                ('code_4_type', models.CharField(blank=True, max_length=12, null=True, verbose_name='Code 4 Lang')),
                ('code_4', models.TextField(blank=True, null=True, verbose_name='CodeBlock 4')),
                ('update', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('answer_votes', models.ManyToManyField(blank=True, related_name='AnswerVotes', to='Code1.profile', verbose_name='Answer Votes')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Code1.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('quiz_id', models.AutoField(primary_key=True, serialize=False)),
                ('quiz_title', models.CharField(max_length=100, verbose_name='Question Title')),
                ('body', ckeditor.fields.RichTextField()),
                ('code_1_type', models.CharField(blank=True, max_length=12, null=True, verbose_name='Code 1 Lang')),
                ('code_1', models.TextField(blank=True, null=True, verbose_name='CodeBlock 1')),
                ('code_2_type', models.CharField(blank=True, max_length=12, null=True, verbose_name='Code 2 Lang')),
                ('code_2', models.TextField(blank=True, null=True, verbose_name='CodeBlock 2')),
                ('code_3_type', models.CharField(blank=True, max_length=12, null=True, verbose_name='Code 3 Lang')),
                ('code_3', models.TextField(blank=True, null=True, verbose_name='CodeBlock 3')),
                ('code_4_type', models.CharField(blank=True, max_length=12, null=True, verbose_name='Code 4 Lang')),
                ('code_4', models.TextField(blank=True, null=True, verbose_name='CodeBlock 4')),
                ('update', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('frames', models.ManyToManyField(blank=True, to='Code1.framework')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Code1.profile')),
                ('quiz_views', models.ManyToManyField(blank=True, related_name='views', to='Code1.profile', verbose_name='Question Views')),
                ('quiz_votes', models.ManyToManyField(blank=True, related_name='votes', to='Code1.profile', verbose_name='Question Votes')),
                ('tags', models.ManyToManyField(blank=True, to='Code1.language')),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('gallery_id', models.AutoField(primary_key=True, serialize=False)),
                ('body_media', models.ImageField(upload_to='Tried', verbose_name='Media')),
                ('update', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quiz1.question')),
            ],
        ),
        migrations.CreateModel(
            name='Answergallery',
            fields=[
                ('angallery_id', models.AutoField(primary_key=True, serialize=False)),
                ('body_media', models.ImageField(upload_to='Answer_Tried', verbose_name='Media')),
                ('update', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Answerimages', to='Quiz1.answer')),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quiz1.question'),
        ),
    ]
