# Generated by Django 4.0.3 on 2022-07-19 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz1', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
    ]
