# Generated by Django 4.0.3 on 2022-07-19 09:52

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Code1', '0004_alter_tag_user'),
        ('Quiz1', '0002_delete_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('quiz_id', models.AutoField(primary_key=True, serialize=False)),
                ('quiz_title', models.CharField(max_length=100, verbose_name='Question Title')),
                ('body', ckeditor.fields.RichTextField()),
                ('code_1', models.TextField(verbose_name='CodeBlock 1')),
                ('code_2', models.TextField(verbose_name='CodeBlock 2')),
                ('code_3', models.TextField(verbose_name='CodeBlock 3')),
                ('code_4', models.TextField(verbose_name='CodeBlock 4')),
                ('code_5', models.TextField(verbose_name='CodeBlock 5')),
                ('tried_body', ckeditor.fields.RichTextField()),
                ('code_11', models.TextField(verbose_name='CodeBlock 11')),
                ('code_22', models.TextField(verbose_name='CodeBlock 22')),
                ('code_33', models.TextField(verbose_name='CodeBlock 33')),
                ('code_44', models.TextField(verbose_name='CodeBlock 44')),
                ('code_55', models.TextField(verbose_name='CodeBlock 55')),
                ('update', models.DateTimeField(auto_now=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Code1.profile')),
                ('tags', models.ManyToManyField(blank=True, to='Code1.language')),
            ],
        ),
    ]
