# Generated by Django 4.0.3 on 2022-07-19 09:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Quiz1', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='quiz_views',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Views'),
        ),
    ]
