# Generated by Django 4.0.3 on 2022-07-19 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Code1', '0004_alter_tag_user'),
        ('Quiz1', '0004_question_quiz_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='quiz_votes',
            field=models.ManyToManyField(blank=True, related_name='votes', to='Code1.profile'),
        ),
        migrations.AlterField(
            model_name='question',
            name='quiz_views',
            field=models.ManyToManyField(blank=True, related_name='views', to='Code1.profile'),
        ),
    ]
