# Generated by Django 4.0.3 on 2022-07-19 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Code1', '0004_alter_tag_user'),
        ('Quiz1', '0005_question_quiz_votes_alter_question_quiz_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='body_media',
            field=models.ImageField(default=0, upload_to='Tried', verbose_name='Body Media'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='tried_media',
            field=models.ImageField(default=0, upload_to='Tried', verbose_name='Tried Media'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='quiz_views',
            field=models.ManyToManyField(blank=True, related_name='views', to='Code1.profile', verbose_name='Question Views'),
        ),
        migrations.AlterField(
            model_name='question',
            name='quiz_votes',
            field=models.ManyToManyField(blank=True, related_name='votes', to='Code1.profile', verbose_name='Question Votes'),
        ),
    ]
