# Generated by Django 4.0.3 on 2022-08-06 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Code1', '0004_alter_tag_user'),
        ('Quiz1', '0006_question_body_media_question_tried_media_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='code_11',
        ),
        migrations.RemoveField(
            model_name='question',
            name='code_22',
        ),
        migrations.RemoveField(
            model_name='question',
            name='code_33',
        ),
        migrations.RemoveField(
            model_name='question',
            name='code_44',
        ),
        migrations.RemoveField(
            model_name='question',
            name='code_5',
        ),
        migrations.RemoveField(
            model_name='question',
            name='code_55',
        ),
        migrations.RemoveField(
            model_name='question',
            name='tried_body',
        ),
        migrations.RemoveField(
            model_name='question',
            name='tried_media',
        ),
        migrations.AddField(
            model_name='question',
            name='code_1_type',
            field=models.CharField(default=0, max_length=12, verbose_name='Code 1 Lang'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='code_2_type',
            field=models.CharField(default=0, max_length=12, verbose_name='Code 2 Lang'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='code_3_type',
            field=models.CharField(default=0, max_length=12, verbose_name='Code 3 Lang'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='code_4_type',
            field=models.CharField(default=0, max_length=12, verbose_name='Code 4 Lang'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='frames',
            field=models.ManyToManyField(blank=True, to='Code1.framework'),
        ),
    ]
