# Generated by Django 4.0.3 on 2022-08-06 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz1', '0007_remove_question_code_11_remove_question_code_22_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='code_1',
            field=models.TextField(blank=True, null=True, verbose_name='CodeBlock 1'),
        ),
        migrations.AlterField(
            model_name='question',
            name='code_1_type',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Code 1 Lang'),
        ),
        migrations.AlterField(
            model_name='question',
            name='code_2',
            field=models.TextField(blank=True, null=True, verbose_name='CodeBlock 2'),
        ),
        migrations.AlterField(
            model_name='question',
            name='code_2_type',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Code 2 Lang'),
        ),
        migrations.AlterField(
            model_name='question',
            name='code_3',
            field=models.TextField(blank=True, null=True, verbose_name='CodeBlock 3'),
        ),
        migrations.AlterField(
            model_name='question',
            name='code_3_type',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Code 3 Lang'),
        ),
        migrations.AlterField(
            model_name='question',
            name='code_4',
            field=models.TextField(blank=True, null=True, verbose_name='CodeBlock 4'),
        ),
        migrations.AlterField(
            model_name='question',
            name='code_4_type',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Code 4 Lang'),
        ),
    ]
