# Generated by Django 4.0.3 on 2022-08-08 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz1', '0008_alter_question_code_1_alter_question_code_1_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='body_media',
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('gallery_id', models.AutoField(primary_key=True, serialize=False)),
                ('body_media', models.ImageField(upload_to='Tried', verbose_name='Media')),
                ('update', models.DateTimeField(auto_now=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quiz1.question')),
            ],
        ),
    ]
