# Generated by Django 4.0.3 on 2022-09-08 08:47

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Code1', '0004_alter_tag_user'),
        ('Quiz1', '0009_remove_question_body_media_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('answer_id', models.AutoField(primary_key=True, serialize=False)),
                ('body', ckeditor.fields.RichTextField()),
                ('code_1_type', models.CharField(blank=True, max_length=12, null=True, verbose_name='Code 1 Lang')),
                ('code_1', models.TextField(blank=True, null=True, verbose_name='CodeBlock 1')),
                ('code_2_type', models.CharField(blank=True, max_length=12, null=True, verbose_name='Code 2 Lang')),
                ('code_2', models.TextField(blank=True, null=True, verbose_name='CodeBlock 2')),
                ('code_3_type', models.CharField(blank=True, max_length=12, null=True, verbose_name='Code 3 Lang')),
                ('code_3', models.TextField(blank=True, null=True, verbose_name='CodeBlock 3')),
                ('code_4_type', models.CharField(blank=True, max_length=12, null=True, verbose_name='Code 4 Lang')),
                ('code_4', models.TextField(blank=True, null=True, verbose_name='CodeBlock 4')),
                ('update', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('answer_votes', models.ManyToManyField(blank=True, related_name='AnswerVotes', to='Code1.profile', verbose_name='Answer Votes')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Code1.profile')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quiz1.question')),
            ],
        ),
    ]
