# Generated by Django 4.0.3 on 2022-09-09 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz1', '0010_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answergallery',
            fields=[
                ('angallery_id', models.AutoField(primary_key=True, serialize=False)),
                ('body_media', models.ImageField(upload_to='Answer_Tried', verbose_name='Media')),
                ('update', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quiz1.answer')),
            ],
        ),
    ]
