# Generated by Django 4.0.3 on 2022-09-10 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz1', '0011_answergallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answergallery',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Answerimages', to='Quiz1.answer'),
        ),
    ]
