# Generated by Django 4.0.3 on 2022-07-19 09:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('lang_id', models.AutoField(primary_key=True, serialize=False)),
                ('lang_name', models.CharField(max_length=20, verbose_name='Tag')),
                ('lang_icon', models.ImageField(upload_to='Tags', verbose_name='Language Icon')),
                ('lang_desc', models.TextField(verbose_name='Language Description')),
                ('update', models.DateTimeField(auto_now=True)),
                ('created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tag_id', models.AutoField(primary_key=True, serialize=False)),
                ('tags', models.ManyToManyField(blank=True, to='Code1.language')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('profile_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=20, verbose_name='Full Name')),
                ('profile_pic', models.ImageField(upload_to='profiles')),
                ('info_picture', models.ImageField(upload_to='infoPicture')),
                ('update', models.DateTimeField(auto_now=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Framework',
            fields=[
                ('frame_id', models.AutoField(primary_key=True, serialize=False)),
                ('frame_name', models.CharField(max_length=20, verbose_name='Framework Name')),
                ('frame_icon', models.ImageField(upload_to='Frameworks', verbose_name='Framework Icon')),
                ('frame_desc', models.TextField(verbose_name='Language Description')),
                ('update', models.DateTimeField(auto_now=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Code1.language', verbose_name='Programming Language')),
            ],
        ),
    ]
