# Generated by Django 4.0.3 on 2022-11-21 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Code1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amount',
            fields=[
                ('amount_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount')),
                ('description', models.TextField(verbose_name='Amount Description')),
                ('period', models.CharField(max_length=10, verbose_name='Period')),
                ('update', models.DateTimeField(auto_now=True)),
                ('created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('rec_id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_date', models.DateTimeField()),
                ('expiry', models.DateTimeField()),
                ('update', models.DateTimeField(auto_now=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('amount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Code1.amount')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Code1.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account_id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_date', models.DateTimeField()),
                ('expiry', models.DateTimeField()),
                ('active', models.BooleanField(default=False, verbose_name='Active Status')),
                ('update', models.DateTimeField(auto_now=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('amount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Code1.amount')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Code1.profile')),
            ],
        ),
    ]
