# Generated by Django 4.0.3 on 2022-07-19 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Code1', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
