# Generated by Django 4.0.3 on 2022-11-21 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Code1', '0003_alter_account_amount_alter_account_expiry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Code1.profile'),
        ),
    ]
