# Generated by Django 4.0.3 on 2022-09-10 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Code1', '0004_alter_tag_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(default=0, verbose_name='Bio'),
            preserve_default=False,
        ),
    ]
